### ISSUE TITLE
Move folders over to main ncats repo

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/mvp-module-library#20]
Create a Workflow1 under https://github.com/ncats/translator-workflows

Move the existing day1..n notebooks there

Move the rest of this repo to translator-workflows but rename as translator-module-library

**Comment by cmungall** [comment]
The downside is that this repo is currently private: https://github.com/ncats/translator-workflows/issues/58

**Comment by realmarcin** [comment]
closing, no longer relevant
