### ISSUE TITLE
BioLink package conflicts with biolink-model library

### ISSUE THREAD

**Issue by jaeddy** [NCATS-Tangerine/mvp-module-library#23]
When the **biolink-model** library is installed (`pip install biolink-model`), it creates the package `biolink` with module `model.py`. If I try to subsequently install the client encoded in this repo (`pip install mvp-module-library`), the package defined under `BioLink` seems to fall into a black hole.

I recommend renaming the client package or moving into the `biolink-model` repo.

**Comment by deepakunni3** [comment]
This is now fixed via the new release of mvp-module-library: https://pypi.org/manage/project/mvp-module-library/release/0.1.0/

The packages are now more explicitly named
